version: '2'

services:

  orderer.eapproval.com:
    container_name: orderer.eapproval.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/eapproval.com/orderers/orderer.eapproval.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/eapproval.com/orderers/orderer.eapproval.com/tls/:/var/hyperledger/orderer/tls
        - orderer.eapproval.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.org1.eapproval.com:
    container_name: peer0.org1.eapproval.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org1.eapproval.com
      - CORE_PEER_ADDRESS=peer0.org1.eapproval.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.eapproval.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.eapproval.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.eapproval.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org1.eapproval.com/peers/peer0.org1.eapproval.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.eapproval.com/peers/peer0.org1.eapproval.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org1.eapproval.com:/var/hyperledger/production
    ports:
      - 7051:7051

  peer0.org2.eapproval.com:
    container_name: peer0.org2.eapproval.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org2.eapproval.com
      - CORE_PEER_ADDRESS=peer0.org2.eapproval.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org2.eapproval.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.eapproval.com:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.eapproval.com:9051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org2.eapproval.com/peers/peer0.org2.eapproval.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org2.eapproval.com/peers/peer0.org2.eapproval.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org2.eapproval.com:/var/hyperledger/production
    ports:
      - 9051:9051
