OrdererOrgs:

  - Name: Orderer
    Domain: eapproval.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer

PeerOrgs:

  - Name: Org1
    Domain: org1.eapproval.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Org2
    Domain: org2.eapproval.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
