version: '2.1'

volumes:
  pgdata:
  walletstore:

networks:
  eApproval:

services:
  explorerdb.eapproval.com:
    image: hyperledger/explorer-db:latest
    container_name: explorerdb.eapproval.com
    hostname: explorerdb.eapproval.com
    environment:
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWORD=password
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - eApproval

  explorer.eapproval.com:
    image: hyperledger/explorer:latest
    container_name: explorer.eapproval.com
    hostname: explorer.eapproval.com
    environment:
      - DATABASE_HOST=explorerdb.eapproval.com
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWD=password
      - LOG_LEVEL_APP=debug
      - LOG_LEVEL_DB=debug
      - LOG_LEVEL_CONSOLE=info
      - LOG_CONSOLE_STDOUT=true
      - DISCOVERY_AS_LOCALHOST=false
    volumes:
      - ./explorer-config.json:/opt/explorer/app/platform/fabric/config.json
      - ./ccp:/opt/explorer/app/platform/fabric/ccp
      - ./crypto-config:/tmp/crypto
      - ../bin:/fabric_bin
      - walletstore:/opt/wallet
    command: sh -c "node /opt/explorer/main.js && tail -f /dev/null"
    ports:
      - 8080:8080
    depends_on:
      explorerdb.eapproval.com:
        condition: service_healthy
    networks:
      - eApproval
