version: '2'

networks:
  eApproval:

services:
  ca0:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/root/ca/ca.org1.eapproval.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/root/ca/${EAPPROVAL_CA1_PRIVATE_KEY}
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /root/ca/ca.org1.eapproval.com-cert.pem --ca.keyfile /root/ca/${EAPPROVAL_CA1_PRIVATE_KEY} -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org1.eapproval.com/ca/:/root/ca
    container_name: ca_peerOrg1
    networks:
      - eApproval

  ca1:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/root/ca/ca.org2.eapproval.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/root/ca/${EAPPROVAL_CA2_PRIVATE_KEY}
      - FABRIC_CA_SERVER_PORT=9054
    ports:
      - "9054:9054"
    command: sh -c 'fabric-ca-server start --ca.certfile /root/ca/ca.org2.eapproval.com-cert.pem --ca.keyfile /root/ca/${EAPPROVAL_CA2_PRIVATE_KEY} -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org2.eapproval.com/ca/:/root/ca
    container_name: ca_peerOrg2
    networks:
      - eApproval
