version: '2'

networks:
  eProcurement:

services:

  api1:
    extends:
      file: api-base.yaml
      service: api-base
    ports:
      - 8000:8000

  api2:
    extends:
      file: api-base.yaml
      service: api-base
    ports:
      - 8001:8000